name: Run Tests

# This section defines when the workflow will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This section defines the jobs that will be executed.
jobs:
  # This is the first job, for running backend tests.
  backend-tests:
    # Use the latest version of Ubuntu as the operating system for the runner.
    runs-on: ubuntu-latest
    # Set environment variables required by the backend tests.
    env:
      SECRET_KEY: "a_test_secret_key_that_is_long_enough"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      DATABASE_URL: "sqlite:///:memory:" # Use an in-memory database for tests
    defaults:
      run:
        # Set the default working directory for all steps in this job.
        working-directory: ./backend
    steps:
    # Step 1: Check out your repository code so the workflow can access it.
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up the Python environment.
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Specify the Python version you are using.

    # Step 3: Install the backend dependencies from your requirements.txt file.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the backend tests using pytest.
    - name: Run tests with pytest
      run: pytest

  # This is the second job, for running frontend tests. It will run in parallel with the backend job.
  frontend-tests:
    # Use the latest version of Ubuntu.
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the default working directory for this job.
        working-directory: ./frontend
    steps:
    # Step 1: Check out the repository code.
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up the Node.js environment.
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # UPDATED: Use a more recent LTS version of Node.js.

    # Step 3: Install the frontend dependencies.
    - name: Install dependencies
      run: npm install

    # Step 4: Run the frontend tests using the "test" script from your package.json.
    - name: Run tests with Vitest
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    # This job will only run if both backend-tests and frontend-tests succeed
    needs: [backend-tests, frontend-tests]
    # This condition ensures that the deploy only happens on pushes to the main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Trigger Netlify Deploy
      run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
